---
sudo: false
language: ruby

services:
  - postgresql

cache: bundler

rvm:
  - 2.6.1

before_install:
  - gem install bundler -v 1.17.2

install:
  - gem update --system
  - bundle install --jobs=3 --retry=3 --deployment

before_script:
  - cd spec/integration/dummy_app
  - bundle exec rails db:create
  - bundle exec rails db:test:prepare
  - cd ../../..

script:
  - bundle exec rubocop
  - bundle exec rspec
